name: build-pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build Diff
      run: make diff-all
    - name: Build Verifier
      run: make verifier-all
