name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build
      run: make run-build
    - name: Vet
      run: make run-vet
    - name: Test
      run: make run-tests